name: Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  deploy:
    name: Build my app

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install
        run: |
          npm install

      - name: Update package lists
        run: sudo apt-get update

      - name: Enable multiverse repository
        run: sudo add-apt-repository multiverse

      - name: Install libasound2
        run: sudo apt-get install libasound2

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install ./google-chrome-stable_current_amd64.deb

      - name: Test
        run: CHROME_BIN=$(which chrome) npm run test
