name: Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build my app

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install
        run: |
          npm install

      - name: Test
        run: |
          npm run test
